; ATTRIB.FRM
; This is the forms file for the ATTRIB application
; Mark Riordan   19 October 2001
!Form Main
Attrib: Test of T27 attributes 

Start ~Bright
Start Underline          End Highlight
Start Blink              End Higli
SecureSecure here        End highlight
Start Underline and keep going
       and going
Start ~Bright and keep going
       and going
Start Reverse            End highlight

Start [Left justify     ]
Start Underline [Left Justify   ]  regular text
Start Protected field     End field
Start Right justify    
---------------------------------------
!EndForm
