@ECHO ÕÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¸
@ECHO ³                                          ³
@ECHO ³  R o b o   H E L P                  ° °  ³
@ECHO ³ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ              ° ° ° ° ³
@ECHO ³  PRE Compile Bat                 ° °°° ° °³
@ECHO ³                                  ° °°°  °³
@ECHO ³                                 ° °  °°  ³
@ECHO ³                                  ° °  °° ³
@ECHO ³                                       °°°³
@ECHO ³ B L U E   S K Y   S O F T W A R E      °°³
@ECHO ³                                        °°³
@ECHO ³±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°°°³
@ECHO ³±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°°°°°³
@ECHO ³±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±°°°°°°°°°°°³
@ECHO ³±±±±±±±±±±±±±±±±±±±±±±±°°°°°°°°°°°°°°°°°°°³
@ECHO ÔÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¾
copy "BurSim.hlp" ".\WinHelp4"
copy "BurSim.hlp" "C:\MRR\BURSIM"


@ECHO POST BATCH COMPLETE > "H:\MRR\BURSIM\HELP\RHPOST.~~$"
