/***********************************************************************
 ** ascii.h                                                           **
 **     Ascii Control character Declarations                          **
 **                                                                   **
 ***********************************************************************/

  /* ASCII control characters */

#define NUL     0
#define SOH     1
#define STX     2
#define ETX     3
#define EOT     4
#define ENQ     5
#define ACK     6
#define BEL     7
#define BS      8
#define HT      9
#define LF      10
#define VT      11
#define FF      12
#define CR      13
#define SO      14
#define SI      15
#define DLE     16
#define DC1     17
#define DC2     18
#define DC3     19
#define DC4     20
#define NAK     21
#define SYN     22
#define ETB     23
#define CAN     24
#define EM      25
#define SUB     26
#define ESC     27
#define FS      28
#define GS      29
#define RS      30
#define US      31

#define DEL     127

  /* EBCDIC control characters */

#define eNUL     0
#define eSOH     1
#define eSTX     2
#define eETX     3
#define eEOT     55
#define eENQ     45
#define eACK     46
#define eBEL     47
#define eBS      22
#define eHT      5
#define eLF      37
#define eVT      11
#define eFF      12
#define eCR      13
#define eSO      14
#define eSI      15
#define eDLE     16
#define eDC1     17
#define eDC2     18
#define eDC3     19
#define eDC4     60
#define eNAK     61
#define eSYN     50
#define eETB     38
#define eCAN     24
#define eEM      25
#define eSUB     63
#define eESC     39
#define eFS      28
#define eGS      29
#define eRS      30
#define eUS      31

#define eSP      64

#define eDEL     7

#define eNL	 21

